### ISSUE TITLE
Getting failed dependency from BaseConfig

### ISSUE THREAD

**Issue by jessefranklin** [deluan/contentful-migrate#89]
Error: Failed to load config "eslint-config-standard" to extend from.
Referenced from: BaseConfig

**Comment by deluan** [comment]
Hey @jessefranklin sorry for the long delay.

Are you still having this issue? How are you running `ctf-migrate`? Did you install it as a global package or is it a dev dependency in your project?

**Comment by mbaranovski** [comment]
I have exactly the same issue. Package installed globally. Running like this: `ctf-migrate bootstrap -c "content-type-name" -t "XXXXXXXXX" -s "space-id" -e "dev"`
I can see that `importerPath` is defaulting to the directory from which we execute the command + appends __placeholder__.js file (it's eslint logic)


The error stack:
```
  🚨  Failed to perform bootstrap : Error: Failed to load config "eslint-config-standard" to extend from.
Referenced from: BaseConfig
Error: Failed to load config "eslint-config-standard" to extend from.
Referenced from: BaseConfig
    at configMissingError (/usr/local/lib/node_modules/contentful-migrate/node_modules/eslint/lib/cli-engine/config-array-factory.js:265:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/usr/local/lib/node_modules/contentful-migrate/node_modules/eslint/lib/cli-engine/config-array-factory.js:826:23)
    at ConfigArrayFactory._loadExtends (/usr/local/lib/node_modules/contentful-migrate/node_modules/eslint/lib/cli-engine/config-array-factory.js:731:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/usr/local/lib/node_modules/contentful-migrate/node_modules/eslint/lib/cli-engine/config-array-factory.js:660:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/usr/local/lib/node_modules/contentful-migrate/node_modules/eslint/lib/cli-engine/config-array-factory.js:596:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at createConfigArray (/usr/local/lib/node_modules/contentful-migrate/node_modules/eslint/lib/cli-engine/config-array-factory.js:340:25)
    at ConfigArrayFactory.create (/usr/local/lib/node_modules/contentful-migrate/node_modules/eslint/lib/cli-engine/config-array-factory.js:395:16)
    at createBaseConfigArray (/usr/local/lib/node_modules/contentful-migrate/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:86:48)
    at new CascadingConfigArrayFactory (/usr/local/lib/node_modules/contentful-migrate/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:211:30)
    at new CLIEngine (/usr/local/lib/node_modules/contentful-migrate/node_modules/eslint/lib/cli-engine/cli-engine.js:563:36)
    at jsonToScript (/usr/local/lib/node_modules/contentful-migrate/lib/bootstrap/jsonToScript.js:69:18)
    at /usr/local/lib/node_modules/contentful-migrate/lib/bootstrap/generateScripts.js:30:11
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async /usr/local/lib/node_modules/contentful-migrate/node_modules/p-map/index.js:57:15 {
  messageTemplate: 'extend-config-missing',
  messageData: { configName: 'eslint-config-standard', importerName: '' }
}
```

**Comment by kweingart08** [comment]
I'm getting this issue as well. Any fix here?

**Comment by timreimherr** [comment]
@deluan is there a resolution to this issue? I'm getting this same error.

**Comment by Jonathan-Wong-Code** [comment]
Same error here too.

**Comment by deluan** [comment]
@Jonathan-Wong-Code and others having this issue: Can you try running it with `npx`, like this:
```
npx contentful-migrate command [params]
```

**Comment by Jonathan-Wong-Code** [comment]
No dice. I'm actually getting 

Error: BaseConfig » eslint-config-standard:
        Environment key "es2021" is unknown
        
        After installing it locally with eslint...googled and it did an npm ls eslint.

Looks like it's running eslint 6.8 which doesn't support es2021. (I'm just using the default Create-react-app setup)

**Comment by deluan** [comment]
When running contentful-migrate with `npx`, you should not add it to your `package.json`. Is that your case?

**Comment by Jonathan-Wong-Code** [comment]
I've tried both :) same result.

**Comment by summerset-admin** [comment]
Hi, I'm getting the same error

**Comment by stephenmacnaughtan** [comment]
Hi, I'm getting the same error

**Comment by stephenmacnaughtan** [comment]
Update: I was able to successfully  run `yarn ctf-migrate bootstrap` from my project after removing `eslint` from my projects dependencies.

**Comment by aladage** [comment]
I'm having the same issue. Any updates?

**Comment by AndrianMauricio** [comment]
Any updates on this issue? I'm experiencing the same.

**Comment by imrans110** [comment]
Getting the same issue here as well. I guess no updates yet ?

**Comment by bnadeem** [comment]
Globally running ctf-migrate failed for me too.  However when adding it to package.json and using it via `npm run migrate -- bootstra -c banner -s spaceid` worked fine.  Following is my package.json file

```
{
  "name": "simple-migrate",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "migrate": "ctf-migrate"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "contentful-migrate": "^0.17.0"
  }
}
 
```
